version: "3.8"
services:
  db-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sa
      POSTGRES_DB: phrase-learner
    ports:
      - "5433:5432"
